// products.js
const allProducts = [
    {
        name: "Hexa Power® charger pro 2800",
        price : 2499000,
        discountPrice: 2449000,
        category: "Charger",
        description: "Charger Motor Listrik WiFi Hexa Power Pro+ 30A<br>Adjustable 3-30A 3-20A<br>24-92V XT90 : Rp 2.399.000,00 <br>M23 : Rp 2.499.000,00 EU Supports<br>Bisa untuk :<br>Li-ion<br>83-84V M23<br>83-84V XT90<br>Gesits <br>Polytron FoxR <br>Adora<br>tyranno<br>sprinto<br>Uwinfly<br>LiFePO4 :<br>87.6V M23<br>87.6V XT90",
        images: ["uploads/charger pro 2800 ukuran.jpeg", "uploads/spec charger pro 2800.jpeg", "uploads/fisik charger pro 2800.jpeg"]
    },
    {
        name: "Hexa Power® charger pro 1850",
        price: 1499000,
        discountPrice: 1449000,
        category: "Charger",
        description: "Charger Motor Listrik Knop Putar<br>Hexa Power Air<br>Adjustable Tegangan 10-92.4V<br>Adjustable Arus 3-20A <br>Socket XT90 : Rp 1.399.000,00 <br>M23 : Rp 1.499.000,00 EU Supports<br>Bisa untuk :<br>Li-ion<br>84V M23<br>83-84V XT90<br>Gesits <br>Polytron FoxR <br>Adora<br>tyranno<br>sprinto<br>Uwinfly<br>Alva Cervo (with Adapter)<br><br><br>Note : <br>1. Charger Garansi 1 bulan",
        images: ["uploads/ukuran charger pro 1850.jpeg", "uploads/spec charger pro 1850.jpeg", "uploads/fisik charger pro 1850.jpeg"]
    },
        {
        name: "Hexa Power® Smart BMS Support UART / CAN / RS485 60/120A Aktif dan pasif balancer 1A",
        price:770000,
        discountPrice: 689900,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-60P Support 10S-24S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-60P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 60A dan arus puncak (peak) hingga 120A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-60P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 60A<br>Arus Puncak (Peak Current): 120A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-60P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 100A(1).jpeg"]
    },  
    {
        name: "Hexa Power® Smart BMS Support CANBUS GESITS 50/100A Aktif dan pasif balancer 1A",
        price: 1100000,
        discountPrice: 1049000,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-50P Support 10S-24S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-50P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 50A dan arus puncak (peak) hingga 100A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-50P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 50A<br>Arus Puncak (Peak Current): 100A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-50P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 50A.jpeg"]
    }, 
    {
        name: "Hexa Power® Smart BMS Support UART / CAN / RS485 80/160A Aktif dan pasif balancer 1A",
        price:825000,
        discountPrice: 739900,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-80P Support 10S-24S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-80P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 80A dan arus puncak (peak) hingga 160A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-80P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 80A<br>Arus Puncak (Peak Current): 160A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-80P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 100A(1).jpeg"]
    }, 
    {
        name: "Hexa Power® Smart BMS Support UART / CAN / RS485 100/200A Aktif dan pasif balancer 1A",
        price:880000,
        discountPrice: 799000,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-100P Support 10S-24S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-100P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 100A dan arus puncak (peak) hingga 200A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-100P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 100A<br>Arus Puncak (Peak Current): 200A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-100P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 100A(1).jpeg","uploads/BMS 100A kabel.jpeg"]
    },   
    {
        name: "Hexa Power® Smart BMS Support UART / CAN / RS485 120/240A Aktif dan pasif balancer 1A",
        price:990000,
        discountPrice: 899000,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-120P Support 10S-24S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-120P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 120A dan arus puncak (peak) hingga 240A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-120P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 120A<br>Arus Puncak (Peak Current): 240A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-120P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 100A(1).jpeg"]
    },  
    {
        name: "Hexa Power® Smart BMS Support UART / CAN / RS485 / 32s 60/120A Aktif dan pasif balancer 0.6A",
        price:1899000,
        discountPrice: 1799000,
        category: "BMS",
        description: "BMS Smart Hexa Power HP-B24S-120P Support 24-32S Active Passive Balance 1A<br>Deskripsi Produk:<br>Lindungi dan optimalkan performa baterai rakitan Anda dengan HEXA POWER Smart BMS.<br>Hexa Power Smart BMS seri HP-B24S-120P adalah solusi manajemen baterai canggih yang dirancang untuk sistem baterai Lithium (Li-ion/LiFePO4) dengan konfigurasi seri yang fleksibel (10S hingga 24S). Dilengkapi dengan teknologi penyeimbang ganda (Aktif & Pasif), BMS ini memastikan setiap sel baterai Anda tetap awet dan memiliki performa maksimal.<br>Sangat cocok untuk aplikasi PLTS (Solar Home System), Sepeda/Motor Listrik (EV), dan Power Wall.<br>Fitur Unggulan:<br>✅ Dual Balancing Technology: Memiliki fitur penyeimbang Aktif dan Pasif (1A) yang bekerja efektif meratakan tegangan antar sel, memperpanjang umur baterai secara signifikan.<br>✅ High Power Output: Mampu menangani arus kontinu hingga 120A dan arus puncak (peak) hingga 240A, cocok untuk beban berat.<br>✅ Flexible Series: Dapat digunakan untuk berbagai konfigurasi baterai mulai dari 10 Seri hingga 24 Seri.<br>✅ Smart Interfaces: Dilengkapi berbagai port koneksi lengkap:<br>LCD: Untuk layar monitoring eksternal.<br>GPS: Support modul GPS (untuk tracking lokasi pada kendaraan listrik).<br>TEMP: Sensor suhu untuk proteksi panas berlebih.<br>SW: Port switch on/off.<br>COM: Port komunikasi data.<br>Spesifikasi Teknis:<br>Merk: HEXA POWER®<br>Model/Tipe: HP-B24S-120P<br>Jenis: Smart BMS,<br>Jumlah Seri Baterai: 10S ~ 24S (Adjustable)<br>Arus Kontinu (Continuous Current): 120A<br>Arus Puncak (Peak Current): 240A<br>Tipe Balancing: Aktif - Pasif (Hybrid)<br>Arus Balancing: 1A<br>Port Koneksi: HEAT, COM, SW, LCD, TEMP, GPS<br>Kelengkapan dalam Paket:<br>1x Unit Smart BMS HEXA POWER HP-B24S-120P<br>1x Kabel/Socket Wiring (Balancing Wires)<br>(Tambahkan item lain jika ada, misal: Sensor suhu, Modul Bluetooth, atau Baut)<br>Catatan Penting:<br>Pemasangan Profesional: Pastikan pemasangan dilakukan oleh teknisi yang mengerti skema kelistrikan baterai lithium. Kesalahan pemasangan kabel (wiring) dapat merusak BMS.<br>Konfigurasi: Pastikan urutan kabel balancing (B-, B1, B2... dst) sesuai dengan diagram yang tertera pada unit.<br>Segera amankan investasi baterai Anda dengan BMS berkualitas tinggi dari Hexa Power! Stok terbatas, silakan diorder.",
        images: ["uploads/BMS 100A(1).jpeg"]
    },  
    {
        name: "Hexa Power® Layar display 2.8 inci HEXA POWER Bluetooth",
        price:299000,
        discountPrice: 279900,
        category: "Aksesoris",
        description: "Pantau kondisi baterai kendaraan listrik, solar panel, atau sistem penyimpanan energi dengan mudah dan akurat menggunakan Display Monitor BMS Hexa Power 2.8inci.Layar ini dirancang untuk menampilkan semua data penting dari Baterai Management System (BMS) Anda secara real-time, dengan tampilan yang jelas dan mudah dibaca.<br> ✨ Fitur & Keunggulan Utama<br>1. Layar LCD Warna 2.8 inci yang Jelas<br>Tampilan layar besar berwarna, dengan angka dan grafik yang mudah dibaca bahkan di bawah sinar matahari. Menampilkan informasi dengan antarmuka yang intuitif.<br><br>2. Koneksi Bluetooth Nirkabel<br><br>Terhubung ke BMS Anda via Bluetooth untuk menampilkan data secara real-time. Tanpa kabel tambahan, pemasangan lebih rapi dan fleksibel.<br>3. Pantau Semua Data Penting Baterai<br>- SOC (State of Charge): Persentase kapasitas baterai tersisa<br>- Tegangan Baterai (Voltage): Tegangan utama dan tegangan sel terendah/tertinggi<br>- Arus (Current): Arus pengisian atau pengosongan<br>- Suhu (Temperature): Suhu baterai<br>- Status Sistem: Indikator STBY (Standby), alarm, dan koneksi Bluetooth<br>4. Desain Kokoh & Kompak<br>Housing berkualitas tinggi, tahan lama, dan mudah dipasang di dashboard kendaraan atau panel kontrol sistem Anda.<br><br>📋 Spesifikasi Produk<br>- Merek: Hexa Power<br>- Ukuran Layar: 2.8 inci LCD Warna<br>- Konektivitas: Bluetooth<br>- Tampilan Utama:<br>- SOC (Persentase Kapasitas Baterai)<br>- Tegangan Utama (V)<br>- Arus (A)<br>- Tegangan Sel (V)<br>- Suhu (°C)<br>- Status & Indikator<br>- Daya: Ditenagai langsung dari sistem BMS<br>- Cocok untuk: Semua jenis sistem BMS yang mendukung komunikasi Bluetooth Hexa Power (EV, motor listrik, solar panel, dll.)<br>🛠️ Kegunaan Utama<br>✅ Memantau sisa daya baterai kendaraan listrik<br>✅ Melihat tegangan dan arus pengisian/pengosongan secara real-time<br>✅ Mendeteksi suhu baterai untuk keamanan<br>✅ Memantau kesehatan sel baterai<br>✅ Pemasangan mudah di dashboard kendaraan atau panel kontrol<br><br>📌 Catatan Penting<br>Pastikan BMS Anda mendukung koneksi Bluetooth Hexa Power sebelum membeli. Display ini dirancang untuk bekerja dengan BMS Hexa Power yang kompatibel.Produk baru, teruji, dan dikemas dengan aman untuk menghindari kerusakan saat pengiriman.",
        images: ["uploads/layar display.jpeg"]
    },  
    {
        name: "Hexa Power® Baterai 55ah",
        price: "-",
        category: "Baterai",
        description: "Baterai Lithium performa tinggi dengan kapasitas 60V 20Ah. Cocok untuk modifikasi motor listrik harian. Tahan hingga 1000 cycle pengisian.",
        images: ["uploads/baterai.jpg"]
    },   
    {
        name: "Hexa Power® Baterai 80ah",
        price: "-",
        category: "Baterai",
        description: "Baterai Lithium performa tinggi dengan kapasitas 60V 20Ah. Cocok untuk modifikasi motor listrik harian. Tahan hingga 1000 cycle pengisian.",
        images: ["uploads/baterai80ah.jpeg"]
    },
    {
        name: "Hexa Power® Baterai 66AH +GPS",
        price: "-",
        category: "Baterai",
        description: "Baterai Lithium performa tinggi dengan kapasitas 60V 20Ah. Cocok untuk modifikasi motor listrik harian. Tahan hingga 1000 cycle pengisian.",
        images: ["uploads/baterai 66AH +GPS.jpeg"]
    },
    {
       name: "Hexa Power® soket M23 male",
        price:99000,
        discountPrice: 94900,
        category: "Aksesoris",
        description: "Hexa Power M23 Male Plug - Konektor Daya 40A Heavy Duty Waterproof IP67<br>Konektor daya M23 Male dari Hexa Power, dirancang untuk arus tinggi hingga 40A. Cocok untuk EV, charger, panel surya, dan peralatan industri.<br>✅ Max 40A, arus tinggi stabil minim panas<br>✅ IP67 waterproof & anti debu<br>✅ Pin berlapis emas, tahan korosi<br>✅ Sistem twist lock anti lepas & tahan getaran<br>✅ Material kokoh, awet jangka panjang",
        images: ["uploads/soket M23 male.jpeg"] 
    }, 
    {
        name: "Hexa Power® Lampu Biled Projector Hexa Power 1.6 inci Blue Lens 40W 8000lm 6000K i set",
        price: 550000,
        discountPrice: 495000,
        category: "Elektronika",
        description: "💡 Lampu Biled Projector Hexa Power 1.6 inci Blue Lens 40W 8000lm 6000K<br>✅ Deskripsi Produk<br>Upgrade pencahayaan motor atau kendaraan Anda dengan Lampu Biled Projector Hexa Power 1.6 yang super terang dan presisi! Dirancang dengan lensa biru premium, lampu ini memberikan cahaya fokus, anti silau, dan tampilan modern dengan suhu cahaya natural 6000K. Cocok untuk motor listrik, motor bebek, atau modifikasi lampu utama kendaraan.<br>✨ Fitur & Keunggulan Utama<br>✅ Cahaya Super Terang 8000lm (Real 40W)<br>Output cahaya hingga 8000lm dengan daya 40W, menerangi jalan lebih jauh dan jelas di malam hari tanpa overheat.<br>✅ Lensa Biru Premium Anti Silau<br>Lensa biru khusus yang memfokuskan cahaya, mengurangi silau ke kendaraan lawan, dan menghasilkan cahaya yang lebih tajam dan terfokus.<br>✅ Suhu Cahaya 6000K Natural White<br>Cahaya putih natural 6000K yang nyaman di mata, tidak terlalu kuning atau terlalu biru, memberikan visibilitas optimal di malam hari.<br>✅ Dual Beam (Near + Far) dalam 1 Unit<br>Bekerja sebagai lampu dekat dan jauh sekaligus: cahaya lebar untuk area dekat dan sinar panjang untuk jarak jauh.<br><br>✅ Desain Heatsink Aluminium Kokoh & Tahan Panas<br>Body dengan sirip pendingin yang luas, membuat lampu tetap dingin meskipun menyala lama, awet dan tidak mudah rusak.<br>✅ Ukuran Kompak 1.6 inci <br>Cocok dipasang di berbagai jenis motor (matic, sport, bebek) atau sebagai lampu tambahan di kendaraan Anda.<br><br>📋 Spesifikasi Teknis<br>- Merek: Hexa Power<br>- Tipe: Biled Projector 1.6<br>- Lensa: Blue Lens Premium<br>- Daya: Real 40W<br>- Lumen: 8000lm<br>- Suhu Warna: 6000K (Natural White)<br>- Beam: Dual (Near + Far)<br>- Material: Aluminium Alloy (Heatsink) + Kaca Optik<br>- Tegangan: DC 12V-24V (Cocok untuk motor & kendaraan)<br>- Ukuran: 1.6 inci (Diameter lensa)<br>- Tingkat Perlindungan: Bukan Waterproof (tidak disarankan terkena air/hujan langsung)<br>- Kondisi: Baru, teruji sebelum dikirim<br><br>🛠️ Cocok Untuk Aplikasi<br>- Modifikasi lampu utama motor (matic, sport, bebek, motor listrik)- Kendaraan offroad/ATV dengan perlindungan tambahan<br>- Penggunaan dalam ruangan atau area tertutup",
        images: ["uploads/Lampu.jpeg"]
    },
    {
        name: "Hexa Power® Tas Charger Hard Case Pelindung Charger & Aksesoris",
        price: 189000,
        discountPrice: 169000,
        category: "Aksesoris",
        description: " Lindungi charger kendaraan listrik, kabel, dan aksesoris penting Anda dengan Tas Charger Hexa Power Hard Case. Dirancang khusus untuk melindungi barang-barang elektronik Anda dari benturan, goresan, dan debu, saat disimpan atau dibawa bepergian.<br> ✨ Fitur & Keunggulan Utama<br>✅ Desain Hard Case Kokoh & Tahan BenturanTerbuat dari material EVA keras berkualitas tinggi, tas ini melindungi charger dari benturan, tekanan, dan goresan selama transportasi atau penyimpanan.<br>✅ Interior Lembut Anti Gores<br>Bagian dalam dilapisi kain lembut yang menjaga permukaan charger dan aksesoris Anda tetap mulus, tidak mudah tergores.<br>✅ Kompartemen Praktis<br>Terdapat ruang utama untuk charger, serta kompartemen di tutup untuk menyimpan kabel, adaptor, atau barang kecil lainnya. Semua tetap rapi di satu tempat.<br>✅ Tahan Debu & Ringkas<br>Desain tertutup rapat, menjaga barang-barang dari debu dan kotoran. Ukuran kompak mudah dimasukkan ke dalam bagasi motor, tas, atau lemari.<br>✅ Mudah Dibawa & Awet<br>Material berkualitas tinggi membuat tas ini tahan lama, tidak mudah sobek, dan nyaman dibawa bepergian.<br><br>📋 Spesifikasi Produk<br>- Merek: Hexa Power<br>- Tipe: Hard Case Tas Charger<br>- Material Luar: EVA Hard Shell Tahan Benturan<br>- Material Dalam: Kain Lembut Anti Gores<br>- Warna: Hitam (sesuai gambar)<br>- Fitur Tambahan: Kompartemen di tutup untuk aksesoris<br>- Penggunaan: Untuk menyimpan dan melindungi charger EV, kabel daya, atau aksesoris elektronik lainnya<br><br>🛠️ Cocok Untuk<br>- Charger kendaraan listrik (motor listrik, sepeda listrik)<br>- Kabel daya, adaptor, dan aksesoris elektronik<br>- Perlindungan barang elektronik saat dibawa bepergian<br>- Penyimpanan rapi di rumah atau di bagasi kendaraan<br><br> 📌 Catatan Penting<br>Produk baru, kokoh, dan siap digunakan. Pastikan ukuran tas sesuai dengan charger Anda sebelum membeli.",
        images: ["uploads/tas charger.jpeg"]
    },
    {
        name: "Hexa Power® Smart Keyless Motor Listrik 72V ",
        price: "-",
        category: "Aksesoris",
        description: "🔑 Smart Keyless Motor Listrik 72V | Aman & Modern (HEXA POWER)<br>Smart Keyless 72V HEXA POWER adalah sistem kunci pintar khusus motor listrik 72V yang memberikan keamanan ekstra dan kemudahan penggunaan. Tanpa anak kunci, cukup dengan remote – motor lebih aman, praktis, dan modern.<br>⭐ Keunggulan Produk:<br>✅ Sistem keyless remote (tanpa kunci)<br>✅ Khusus motor listrik 72V<br>✅ Keamanan lebih tinggi, anti maling<br>✅ Respon cepat & stabil<br>✅ Desain ringkas & kuat<br>✅ Mudah dipasang<br>🔧 Spesifikasi Singkat:<br>Tipe: Smart Keyless System<br>Tegangan: 72V<br>Kontrol: Remote wireless<br>Aplikasi: Motor listrik<br>🎯 Cocok Untuk:<br>Motor listrik 72V<br>Upgrade sistem keamanan<br>Pengganti kunci manual<br>Penggunaan harian & profesional<br>📦 Isi Paket:<br>1x Modul Smart Keyless<br>2x Remote HEXA POWER<br>Kabel & aksesoris standar<br>💯 Produk berkualitas & siap pakai<br>Aman | Praktis | Tampilan modern",
        images: ["uploads/keyless chain.jpeg"]
    },
    {
        name: "Hexa Power® Smart Solder JBC 470",
        price: 1600000,
        category: "Elektronika",
        description: "🔥 Smart Solder JBC 470 | Solder Station Profesional Presisi Tinggi<br>Smart Solder JBC 470 adalah solder station profesional dengan teknologi pintar untuk hasil solder rapi, cepat, dan stabil. Cocok untuk teknisi elektronik, servis PCB, hingga industri manufaktur.<br>⭐ Keunggulan Produk:<br>✅ Pemanasan super cepat<br>✅ Suhu stabil & presisi tinggi<br>✅ Teknologi smart – hemat daya<br>✅ Aman untuk komponen sensitif<br>✅ Kompatibel berbagai mata solder JBC<br>✅ Kualitas industri & tahan lama<br>🔧 Spesifikasi Singkat:<br>Tipe: Smart Solder Station<br>Model: JBC 470<br>Kontrol suhu digital<br>Desain profesional & ergonomis<br>🎯 Cocok Digunakan Untuk:<br>Servis HP & laptop<br>Perbaikan PCB & SMD<br>Bengkel elektronik<br>Produksi & maintenance industri<br>📦 Isi Paket:<br>1x Unit Smart Solder JBC 470<br>1x Handle solder<br>Kabel & aksesoris standar<br>(Isi paket dapat menyesuaikan)<br>💯 Original & kualitas premium<br>Siap pakai | Pengiriman aman | Support teknisi",
        images: ["uploads/solder.jpeg"]
    },
    {
        name: "Hexa Power® Adapter SPKLU Type 2",
        price: 270000,
        category: "Aksesoris",
        description: "🔌 Adapter SPKLU Type 2 | Pin Tembaga | Untuk Motor Listrik<br>Adapter SPKLU Type 2 ini dirancang khusus untuk memudahkan pengisian daya motor listrik di stasiun pengisian umum (SPKLU) dengan konektor Type 2. Menggunakan pin berbahan tembaga murni untuk konduktivitas maksimal, pengisian lebih stabil, aman, dan efisien.<br>⭐ Keunggulan Produk:<br>✅ Kompatibel SPKLU konektor Type 2<br>✅ Pin tembaga berkualitas tinggi – arus lebih stabil<br>✅ Minim panas & tahan arus besar<br>✅ Konstruksi kuat & presisi<br>✅ Aman untuk penggunaan harian<br>✅ Plug & play, mudah digunakan<br>🔧 Spesifikasi Singkat:<br>Tipe: Adapter Charger SPKLU<br>Konektor: Type 2<br>Material pin: Tembaga<br>Aplikasi: Motor listrik<br>Fungsi: Penghubung charger SPKLU ke motor listrik<br>🎯 Cocok Digunakan Untuk:<br>Pengisian motor listrik di SPKLU umum<br>Upgrade sistem charging motor listrik<br>Pengguna motor listrik harian & fleet<br>📦 Isi Paket:<br>1x Adapter SPKLU Type 2<br>⚠️ Catatan Penting:<br>Pastikan kompatibilitas dengan sistem motor listrik Anda<br>Disarankan pemasangan & penggunaan sesuai standar keamanan<br>💯 Solusi praktis & aman untuk charging motor listrik di SPKLU.<br>Kuat | Stabil | Tahan lama",
        images: ["uploads/tempat kabel.jpeg", "uploads/tempat kabel2.jpeg",]
    },
 
];